# Generated by Django 5.1.6 on 2025-04-07 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bordereau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_bordereau', models.DateField()),
                ('no_bordereau', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompagnieAerienne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata', models.CharField(max_length=3, unique=True)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelNavigant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn', models.CharField(max_length=8, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_de_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10, null=True)),
                ('statut_pn', models.CharField(blank=True, max_length=100, null=True)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnels', to='expertise.compagnieaerienne')),
            ],
        ),
        migrations.CreateModel(
            name='FicheEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_evenement', models.DateField()),
                ('no_facture', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Numéro de facture')),
                ('paiement', models.BooleanField(default=False, verbose_name='Paiement')),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('modalite_paiement', models.CharField(blank=True, choices=[('liquide', 'Liquide'), ('virement', 'Virement'), ('cb', 'Carte Bancaire')], max_length=10, null=True, verbose_name='Modalité de paiement')),
                ('honoraire_cempn', models.IntegerField(default=0, verbose_name='CEMPN')),
                ('honoraire_cs_oph', models.IntegerField(default=0, verbose_name='OPH')),
                ('honoraire_cs_orl', models.IntegerField(default=0, verbose_name='ORL')),
                ('honoraire_cs_labo', models.IntegerField(default=0, verbose_name='Labo AMJ')),
                ('honoraire_cs_lbx', models.IntegerField(default=0, verbose_name='Labstix')),
                ('honoraire_cs_radio', models.IntegerField(default=0, verbose_name='Radio')),
                ('frais_dossier', models.IntegerField(default=0, verbose_name='Frais de dossier')),
                ('cs_cempn', models.BooleanField(default=False)),
                ('cs_oph', models.BooleanField(default=False)),
                ('cs_orl', models.BooleanField(default=False)),
                ('cs_labo', models.BooleanField(default=False)),
                ('cs_lbx', models.BooleanField(default=False)),
                ('cs_radio', models.BooleanField(default=False)),
                ('date_cempn', models.DateField(blank=True, null=True)),
                ('date_cs_oph', models.DateField(blank=True, null=True)),
                ('date_cs_orl', models.DateField(blank=True, null=True)),
                ('date_cs_labo', models.DateField(blank=True, null=True)),
                ('date_cs_lbx', models.DateField(blank=True, null=True)),
                ('date_cs_radio', models.DateField(blank=True, null=True)),
                ('recherche_toxique', models.BooleanField(default=False)),
                ('quote_part_patient', models.BooleanField(default=False)),
                ('paye_par_patient', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('bordereau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='expertise.bordereau')),
                ('medecin_cempn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_cempn', to='expertise.medecin')),
                ('medecin_oph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_oph', to='expertise.medecin')),
                ('medecin_orl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_orl', to='expertise.medecin')),
                ('medecin_radio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_radio', to='expertise.medecin')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='expertise.personnelnavigant')),
            ],
        ),
    ]
