# Generated by Django 5.1.6 on 2025-02-09 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheevenement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ficheevenement',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expertise.personnelnavigant', to_field='dn', verbose_name='DN du personnel'),
        ),
        migrations.AlterField(
            model_name='personnelnavigant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
