# Generated by Django 5.1.6 on 2025-02-09 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0002_alter_ficheevenement_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheevenement',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expertise.personnelnavigant', to_field='dn', verbose_name='Personnel (DN)'),
        ),
    ]
