# Generated by Django 5.1.6 on 2025-04-07 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0002_bordereau_virement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelnavigant',
            name='statut_pn',
            field=models.CharField(blank=True, choices=[('Pilote', 'Pilote'), ('PNC', 'PNC'), ('Controleur aérien', 'Contrôleur aérien')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='FactureMedecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('bordereau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_medecins', to='expertise.bordereau')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expertise.medecin')),
            ],
        ),
    ]
