# Generated by Django 5.1.6 on 2025-04-08 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0003_alter_personnelnavigant_statut_pn_facturemedecin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheevenement',
            name='medecin_labo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_labo', to='expertise.medecin', verbose_name='Médecin laboratoire'),
        ),
        migrations.AlterField(
            model_name='personnelnavigant',
            name='statut_pn',
            field=models.CharField(blank=True, choices=[('Pilote', 'Pilote'), ('PNC', 'PNC'), ('Controleur aérien', 'Contrôleur aérien'), ('Para Pro', 'Para Pro')], max_length=100, null=True),
        ),
    ]
