# Generated by Django 5.1.6 on 2025-02-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0004_alter_ficheevenement_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheevenement',
            name='paye_par_patient',
            field=models.IntegerField(default=0, verbose_name='Payé par le patient'),
        ),
        migrations.AddField(
            model_name='ficheevenement',
            name='quote_part_patient',
            field=models.BooleanField(default=False, verbose_name='Quote-part patient'),
        ),
    ]
