# Generated by Django 5.1.6 on 2025-04-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0004_ficheevenement_medecin_labo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficheevenement',
            old_name='recherche_toxique',
            new_name='cs_toxique',
        ),
        migrations.AddField(
            model_name='ficheevenement',
            name='date_cs_toxique',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficheevenement',
            name='honoraire_cs_toxique',
            field=models.IntegerField(default=0, verbose_name='Toxique'),
        ),
        migrations.AlterField(
            model_name='ficheevenement',
            name='modalite_paiement',
            field=models.CharField(blank=True, choices=[('liquide', 'Liquide'), ('virement', 'Virement'), ('CB', 'Carte Bancaire'), ('Chèque', 'Chèque')], max_length=10, null=True, verbose_name='Modalité de paiement'),
        ),
    ]
