# Generated by Django 5.0.6 on 2025-02-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0005_ficheevenement_paye_par_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheevenement',
            name='medecin_cempn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Médecin CEMPn'),
        ),
        migrations.AddField(
            model_name='ficheevenement',
            name='medecin_oph',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Médecin OPH'),
        ),
        migrations.AddField(
            model_name='ficheevenement',
            name='medecin_orl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Médecin ORL'),
        ),
        migrations.AddField(
            model_name='ficheevenement',
            name='medecin_radio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Médecin RADIO'),
        ),
    ]
