# Generated by Django 5.1.6 on 2025-04-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0005_rename_recherche_toxique_ficheevenement_cs_toxique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN / RIB'),
        ),
    ]
