# Generated by Django 5.0.6 on 2025-02-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0006_ficheevenement_medecin_cempn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
            ],
            options={
                'verbose_name': 'Médecin',
                'verbose_name_plural': 'Médecins',
            },
        ),
        migrations.AlterField(
            model_name='personnelnavigant',
            name='date_de_naissance',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
    ]
