# Generated by Django 5.0.6 on 2025-02-10 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0007_medecin_alter_personnelnavigant_date_de_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheevenement',
            name='medecin_cempn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_cempn', to='expertise.medecin', verbose_name='Médecin CEMPn'),
        ),
        migrations.AlterField(
            model_name='ficheevenement',
            name='medecin_oph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_oph', to='expertise.medecin', verbose_name='Médecin OPH'),
        ),
        migrations.AlterField(
            model_name='ficheevenement',
            name='medecin_orl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_orl', to='expertise.medecin', verbose_name='Médecin ORL'),
        ),
        migrations.AlterField(
            model_name='ficheevenement',
            name='medecin_radio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_radio', to='expertise.medecin', verbose_name='Médecin RADIO'),
        ),
    ]
