# Generated by Django 5.0.6 on 2025-02-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0008_alter_ficheevenement_medecin_cempn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheevenement',
            name='no_facture',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Numéro de facture'),
        ),
        migrations.AlterField(
            model_name='personnelnavigant',
            name='date_de_naissance',
            field=models.DateField(verbose_name='Date de naissance (DD/MM/YYYY)'),
        ),
    ]
