# Generated by Django 5.0.6 on 2025-02-12 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0009_ficheevenement_no_facture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompagnieAerienne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='personnelnavigant',
            name='compagnie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expertise.compagnieaerienne', verbose_name='Compagnie Aérienne'),
        ),
    ]
