# Generated by Django 5.0.6 on 2025-02-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0010_compagnieaerienne_personnelnavigant_compagnie'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelnavigant',
            name='statut_pn',
            field=models.CharField(choices=[('PNT', 'PNT (Pilote)'), ('PNC', 'PNC (Personnel Navigant Commercial)')], default='PNT', help_text='PNT pour pilote, PNC pour hôtesse/steward', max_length=3, verbose_name='Statut PN'),
        ),
    ]
