# Generated by Django 5.0.6 on 2025-02-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0011_personnelnavigant_statut_pn'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelnavigant',
            name='iata',
            field=models.CharField(choices=[('AFR', 'Air France'), ('ATN', 'Air Tahiti Nui'), ('XZY', 'Compagnie fictive')], default='AFR', help_text='Code IATA de la compagnie (ex : AFR, ATN...).', max_length=3, verbose_name='IATA'),
        ),
        migrations.AlterField(
            model_name='personnelnavigant',
            name='statut_pn',
            field=models.CharField(choices=[('PNT', 'PNT (Pilote)'), ('PNC', 'PNC (Personnel Navigant Commercial)')], default='PNT', help_text='(PNT pour pilote, PNC pour hôtesse/steward)', max_length=3, verbose_name='Statut PN'),
        ),
    ]
