# Generated by Django 5.0.6 on 2025-02-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0012_personnelnavigant_iata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compagnieaerienne',
            name='iata',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Code IATA'),
        ),
    ]
